### ISSUE TITLE
hello，Can you sent the dataBase init file?

### ISSUE THREAD

**Issue by wqc1999** [yafeng-Soong/mindmap-manager-backend#1]
你好，可以给我一份数据库初始化脚本吗？

**Comment by yafeng-Soong** [comment]
> 你好，可以给我一份数据库初始化脚本吗？

明天或后天我有空上传一个

**Comment by wqc1999** [comment]
谢谢！

**Comment by yafeng-Soong** [comment]
> 谢谢！
已添加到db中，初始邮箱是123456789@qq.com，密码是gta12345678或者gta123456、gta123456789

**Comment by wqc1999** [comment]
感谢



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 28, 2022 20:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yafeng-Soong/mindmap-manager-backend] hello，Can you sent the dataBase init file? (Issue #1)




  
谢谢！
 ***@***.***，密码是gta12345678或者gta123456、gta123456789
